---
- name: Check NTP synchronization settings on RHEL servers
  hosts: all
  become: yes
  tasks:
    - name: Ensure chrony is installed
      package:
        name: chrony
        state: present

    - name: Check for 'iburst' entries in /etc/chrony.conf
      command: grep 'iburst' /etc/chrony.conf
      register: chrony_iburst
      changed_when: false
      ignore_errors: true

    - name: Check if chronyd service is enabled
      command: systemctl is-enabled chronyd
      register: chronyd_enabled
      changed_when: false
      ignore_errors: true

    - name: Display NTP configuration details
      debug:
        msg: |
          NTP Configuration for {{ inventory_hostname }}:
          - NTP Servers with iburst:
            {% if chrony_iburst.stdout_lines %}
              {{ chrony_iburst.stdout_lines | join(', ') }}
            {% else %}
              No NTP servers with iburst configured
            {% endif %}
          - chronyd service: {{ chronyd_enabled.stdout | default('Not Enabled') }}
