---
- name: Check NTP synchronization settings on RHEL servers
  hosts: all
  become: yes
  tasks:
    - name: Ensure chrony is installed
      package:
        name: chrony
        state: present

    - name: Check for 'iburst' entries in /etc/chrony.conf
      command: grep 'iburst' /etc/chrony.conf
      register: chrony_iburst
      changed_when: false
      ignore_errors: true

    - name: Check if chronyd service is enabled
      command: systemctl is-enabled chronyd
      register: chronyd_enabled
      changed_when: false
      ignore_errors: true

    - name: Display NTP configuration details
      debug:
        msg: |
          NTP Servers (with iburst):
          {{ chrony_iburst.stdout_lines | join('\n') | default('No NTP servers found in chrony.conf') }}

          chronyd service enabled: 
          {{ chronyd_enabled.stdout | default('chronyd service is not enabled') }}
