---
- name: Install NRPE Agent
  hosts: all
  become: yes
  tasks:
    - name: Change directory to /tmp
      command: cd /tmp

    - name: Download NRPE agent tarball
      get_url:
        url: http://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz
        dest: /tmp/linux-nrpe-agent.tar.gz

    - name: Extract NRPE agent tarball
      unarchive:
        src: /tmp/linux-nrpe-agent.tar.gz
        dest: /tmp

    - name: Change directory to extracted NRPE agent directory
      command: cd /tmp/linux-nrpe-agent

    - name: Run full install
      command: ./fullinstall -n -i 172.25.200.134