---
- name: Check how many updates are needed on RHEL/CentOS
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Simulate yum update to get transaction summary
      shell: yum update --assumeno
      register: yum_check
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Extract Transaction Summary from yum output
      debug:
        msg: "{{ yum_check.stdout | regex_search('Transaction Summary.*', multiline=True) }}"
      when: ansible_os_family == "RedHat"
