---
- name: Install UEMS Linux Agent
  hosts: all
  become: true
  tasks:
    - name: Copy UEMS Linux Agent ZIP file from local server to remote
      copy:
        src: /home/ssuadmin/Downloads/LocalOffice_UEMSLinuxAgent.zip
        dest: /tmp/LocalOffice_UEMSLinuxAgent.zip

    - name: Unzip UEMS Linux Agent
      unarchive:
        src: /tmp/LocalOffice_UEMSLinuxAgent.zip
        dest: /tmp