---
- name: Count available yum updates
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Count updates with yum check-update
      shell: yum check-update | wc -l
      register: update_count
      changed_when: false
      failed_when: false

    - name: Show number of available updates
      debug:
        msg: "Available updates on {{ inventory_hostname }}: {{ update_count.stdout }}"
