---
- name: Install UEMS Linux Agent
  hosts: all
  become: true
  tasks:
    - name: Copy serverinfo.json from local server to remote
      copy:
        src: /home/administrator/Downloads/UEMS/serverinfo.json
        dest: /tmp/serverinfo.json

    - name: Copy UEMS Linux Agent binary from local server to remote
      copy:
        src: /home/administrator/Downloads/UEMS/UEMS_LinuxAgent.bin
        dest: /tmp/UEMS_LinuxAgent.bin
        mode: +x

    - name: Execute UEMS Linux Agent installer
      ansible.builtin.shell:
        cmd: "./UEMS_LinuxAgent.bin"
        chdir: "/tmp"