---
- name: Install NCPA and configure
  hosts: all

  tasks:
    - name: Download NCPA package
      get_url:
        url: "https://assets.nagios.com/downloads/ncpa/ncpa-latest.amd64.deb"
        dest: "/tmp/ncpa-latest.amd64.deb"

    - name: Run 'sudo uptime'
      command: sudo uptime
      become: yes
      become_user: administrator

#    - name: Install NCPA package
#      apt:
#        deb: "/tmp/ncpa-latest.amd64.deb"
#        state: present
        
#    - name: Configure NCPA
#      lineinfile:
#        path: "/usr/local/ncpa/etc/ncpa.cfg"
#        regexp: "^community_string = .*"
#        line: "community_string = Nagk2F@hVr3Ls6Tq8Xj@#SSU"

#    - name: Restart NCPA Listener
#      service:
#        name: ncpa_listener
#        state: restarted
