---
- name: Install NCPA and configure
  hosts: all
  become: true
  tasks:
    - name: Gather facts about the system
      ansible.builtin.gather_facts:

    - name: Install NCPA package
      shell: >
        rpm -Uvh https://assets.nagios.com/downloads/ncpa/ncpa-latest.el{{ ansible_distribution_major_version }}.x86_64.rpm
      when: ansible_distribution in ['RedHat', 'CentOS']

    - name: Configure NCPA
      block:
        - name: Set community string in ncpa.cfg
          replace:
            path: /usr/local/ncpa/etc/ncpa.cfg
            regexp: '^community_string = .*'
            replace: 'community_string = Nagk2F@hVr3Ls6Tq8Xj@#SSU'

        - name: Restart NCPA listener
          service:
            name: ncpa_listener
            state: restarted

        - name: Check if firewalld is installed
          ansible.builtin.package_facts:

        - name: Ensure firewalld is installed and running
          ansible.builtin.systemd:
            name: firewalld
            state: started
            enabled: yes
          when: "'firewalld' in ansible_facts.packages"

        - name: Manage firewall ports via shell commands
          shell: >
            firewall-cmd --zone=public --add-port=5693/tcp --permanent && firewall-cmd --reload
          when: ansible_facts.services["firewalld"] is defined and ansible_facts.services["firewalld"].state == "running"
      
      become: true
