---
- name: Uninstall NRPE and xinetd
  hosts: your_target_hosts
  become: true
  tasks:
    - name: Check status of xinetd before uninstallation
      command: systemctl status xinetd
      register: xinetd_status_before
      ignore_errors: yes

    - debug:
        msg: "Status of xinetd before uninstallation: {{ xinetd_status_before.stdout }}"
      when: xinetd_status_before.rc == 0

    - name: Uninstall NRPE
      command: /usr/local/nagios/bin/nrpe-uninstall all
      ignore_errors: yes

    - name: Remove xinetd package
      yum:
        name: xinetd
        state: absent
      ignore_errors: yes

    - name: Check status of xinetd after removal
      command: systemctl status xinetd
      register: xinetd_status_after
      ignore_errors: yes

    - debug:
        msg: "Status of xinetd after removal: {{ xinetd_status_after.stdout }}"
      when: xinetd_status_after.rc == 0
