---
- name: Install NRPE Agent
  hosts: all
  become: yes
  tasks:
    - name: Change directory to /tmp
      command: cd /tmp

    - name: Download NRPE agent tarball
      get_url:
        url: http://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz
        dest: /tmp/linux-nrpe-agent.tar.gz

    - name: Extract NRPE agent tarball
      unarchive:
        src: /tmp/linux-nrpe-agent.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Change directory to extracted NRPE agent directory
      command: cd /tmp/linux-nrpe-agent

    - name: Run full install
      command: /tmp/linux-nrpe-agent/fullinstall -n -i 172.25.200.134
      args:
        chdir: /tmp/linux-nrpe-agent

    - name: Append SSU Configuration to nrpe.cfg
      blockinfile:
        path: /usr/local/nagios/etc/nrpe.cfg
        block: |
          command[check_users]=/usr/local/nagios/libexec/check_users -w 5 -c 10
          command[check_load]=/usr/local/nagios/libexec/check_load -w 15,10,5 -c 30,25,20
          command[check_zombie_procs]=/usr/local/nagios/libexec/check_procs -w 5 -c 10 -s Z
          command[check_total_procs]=/usr/local/nagios/libexec/check_procs -w 150 -c 200
          command[check_all_disks]=/usr/local/nagios/libexec/check_disk -w 20% -c 10% -p /
        marker: "### SSU Ansible Managed Text ###"

    - name: Restart xinetd service
      systemd:
        name: xinetd
        state: restarted

    - name: Run check_all_disks
      command: /usr/local/nagios/libexec/check_nrpe -H 127.0.0.1 -c check_all_disks
      register: nrpe_output

    - name: Display NRPE output
      debug:
        var: nrpe_output.stdout_lines
