---
- name: Check Server Uptime
  hosts: all
  tasks:
    - name: Get Uptime
      command: uptime
      register: uptime_output

    - name: Display Uptime
      debug:
        msg: "Uptime on {{ inventory_hostname }} is {{ uptime_output.stdout }}"
