---
- name: Check for presence of virbr0 interface
  hosts: all
  tasks:
    - name: Run command to check for virbr0 interface
      command: ip addr show
      register: ip_output

    - name: Search for virbr0 in command output
      debug:
        msg: "virbr0 interface found."
      when: "'virbr0' in ip_output.stdout"

    - name: Report missing virbr0 interface
      debug:
        msg: "virbr0 interface missing."
      when: "'virbr0' not in ip_output.stdout"
