---
- name: Run PowerhShell Query
  hosts: all
  gather_facts: no
  tasks:
    - name: Run PowerShell Query
      ansible.windows.win_shell: Get-WUHistory | Where-Object { $_.Title -like '*2024-02 Cumulative Update for Windows*' }
      register: query_output

    - name: Display service objects
      debug:
        msg: "{{ query_output.stdout_lines | select('search', 'Installation') | list }}"